version: '3'

services:
  personal:
    build: ./
    image: personal
    user: "1000"
    volumes:
      - ../:/code/
    ports:
      - "80:8000"
    working_dir: /code/
    command: > 
      bash -c "/code/deployment/entrypoint.sh"